[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
pyloid = "^0.20.1"
pyinstaller = "^6.11.1"

[tool.pyright]
venvPath = "./"
venv = "venv-pyloid"
pythonVersion = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
