[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"

[tool.pyright]
venvPath = "./"
venv = "venv-pyloid"
pythonVersion = "3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
